# Generated by Django 5.1.7 on 2025-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
