# Generated by Django 5.1.7 on 2025-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_remove_account_username_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='default_username', max_length=50),
            preserve_default=False,
        ),
    ]
