# Generated by Django 5.1.7 on 2025-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/OIP_1.webp', upload_to='userprofile'),
        ),
    ]
