# Generated by Django 5.1.7 on 2025-09-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='StoreApp.product'),
        ),
    ]
