# Generated by Django 5.1.7 on 2025-09-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_alter_variations_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('storage', 'storage')], max_length=100),
        ),
    ]
