# Generated by Django 5.1.7 on 2025-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
