# Generated by Django 5.1.7 on 2025-08-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
