# Generated by Django 5.1.7 on 2025-09-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_alter_cartitem_is_active'),
        ('StoreApp', '0004_alter_variations_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='StoreApp.variations'),
        ),
    ]
