# Generated by Django 5.1.7 on 2025-09-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0005_rename_payment_orderproduct_payment_order_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
