# Generated by Django 5.1.7 on 2025-09-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
